### PR TITLE
On screen keyboard

### PR DESCRIPTION
**Pull request by cibersheep**
Sorry. I'm still confused with github.
I wanted to do a pull request for [e29b474](https://github.com/cibersheep/parchment/commit/e29b47440bd9e27e02f032cedde4dbd1fdb1a296) that should make on screen keyboard to appear while playing.

### CODE REVIEW

**Comment by curiousdannii** [comment]
I don't think I want the keyboard to stay up all the time - it will take up too much screen space.

**Comment by cibersheep** [comment]
I see what you mean. In my experience is that having to tap every time after a command is a breaking the game.
It could be optional, something not by default but as `option=osk_on`

**Comment by curiousdannii** [comment]
I've rebased the master branch so this can't be merged any longer in any case.

And FYI, I am also intending to switch to using GlkOte, even for the Z-Machine, and probably won't be updating Parchment's current UI layer unless there are major bugs.

**Comment by cibersheep** [comment]
Ok. Thanks foe the information.

**Comment by curiousdannii** [comment]
Parchment doesn't currently have any kind of options panel, but it would be good to have one in the future, and this be something that would make sense to be an option then. :)

**Comment by cibersheep** [comment]
I was thinking more as a flag in index (similar to the json options={"width":35} aproach).
That could solve [issue 27](https://github.com/curiousdannii/parchment/issues/27)
But if you're planning to move to glkote, with quixe there's no focus issue.

**Pull request closed without merging**
